# List of GitHub teams.
- name: members
  description: The @:org organization team
  scope: :org/*
  permission: TRIAGE
  member: :orgTeam/member
  maintainer: :orgTeam/lead
- name: contributors
  parent: members
  description: Contributors of the @:org organization team
  scope: :org/*
  permission: TRIAGE
  member: :orgTeam/contributor
  maintainer: :orgTeam/lead
- name: maintainers
  parent: members
  description: Maintainers of the @:org organization team
  scope: :org/*
  permission: WRITE
  member: :orgTeam/maintainer
  maintainer: :orgTeam/lead
- name: mergers
  parent: maintainers
  description: '@:org maintainers with write rights'
  scope: :org/*
  permission: WRITE
  member: :orgTeam/merger
  maintainer: :orgTeam/lead
- name: releasers
  parent: maintainers
  description: '@:org maintainers with release rights'
  scope: :org/*
  permission: MAINTAIN
  member: :orgTeam/releaser
  maintainer: :orgTeam/lead
- name: moderators
  description: The @:collective collective moderation team
  scope: :org/*
  permission: ADMIN
  member: moderation/maintainer
  maintainer: :orgTeam/lead
- name: core
  description: The @:collective collective core team
  scope: :org/*
  permission: ADMIN
  member: core/maintainer
  maintainer: :orgTeam/lead
