const trough = require('trough')
const configure = require('./configure')
const members = require('./members')
const teams = require('./teams')
const repos = require('./repos')

module.exports = trough()
  .use(configure)
  .use(members)
  .use(teams)
  .use(repos)
